services:
  - type: web
    name: user-service
    env: docker
    rootDir: user-service
    dockerfilePath: Dockerfile

  - type: web
    name: event-catalog-service
    env: docker
    rootDir: event-catalog-service
    dockerfilePath: Dockerfile

  - type: web
    name: booking-service
    env: docker
    rootDir: booking-service
    dockerfilePath: Dockerfile

  - type: web
    name: payment-service
    env: docker
    rootDir: payment-service
    dockerfilePath: Dockerfile
