services:
  - type: web
    name: event-catalog-service
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8082
      - key: EUREKA_ENABLED
        value: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false
